### ISSUE TITLE
how to use highlight.js?

### ISSUE THREAD

**Issue by mvalitov** [dim0627/hugo_theme_beg#15]
Hi, I would like to use highlight.js. I wrote
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/styles/atom-one-dark.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

in my_site/themes/hugo_theme_beg/layouts/partials/meta.html, and
```
~~~ruby
# The Greeter class
class Greeter
  def initialize(name)
    @name = name.capitalize
  end

  def salute
    puts "Hello #{@name}!"
  end
end

g = Greeter.new("world")
g.salute
~~~
```
in my post, but it does not work. Maybe you need to connect highlight in another place?

**Comment by dim0627** [comment]
I tried your code but does not reproduce X(

<img width="497" alt="screen shot 2017-03-26 at 20 55 33" src="https://cloud.githubusercontent.com/assets/6571653/24331020/96183d94-1266-11e7-9763-885827dff140.png">

**Comment by mvalitov** [comment]
Thanks, I got the correct work after I changed the file
`my_site/themes/hugo_theme_beg/layouts/_default/baseof.html`
line 7:
`    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/solarized_dark.min.css">`
