### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [dim0627/hugo_theme_beg#19]
Current behavior, main page and single post page:
---
![current-main](https://user-images.githubusercontent.com/712534/33841411-b70a5276-dea8-11e7-8e0f-1dbe54de5c24.png)
![current-single](https://user-images.githubusercontent.com/712534/33841412-b739176e-dea8-11e7-82d0-36982fa8a23b.png)
===
Images have max-width set to 100%:
---
![fixed-main](https://user-images.githubusercontent.com/712534/33841450-d0a93738-dea8-11e7-9ae6-7b1898736061.png)
![fixed-single](https://user-images.githubusercontent.com/712534/33841451-d0c85bcc-dea8-11e7-91d9-85e3e77aa8d1.png)
===
I don't think it's a feature, seems like a bug - could you please introduce this css property to make my pictures look nice again?;)

**Comment by dim0627** [comment]
OK, I'll revert that merge commit temporary.

**Comment by dim0627** [comment]
This is not related PR 🤔 ?
https://github.com/dim0627/hugo_theme_beg/pull/20

I'll try reproduce tonight.
Please wait 🙏

**Comment by dim0627** [comment]
@paskal 
Do you use this code?

```
{{% img src="images/image.jpg" %}}
```

**Comment by paskal** [comment]
It's not related to #18. I use `![image description](image link)`, I am using pure markdown syntax to keep things simple, I've just migrated from other platform and it doesn't work the way it used to on other platform.

**Comment by dim0627** [comment]
hmm, Okay.

I made commit just now.
https://github.com/dim0627/hugo_theme_beg/commit/fdc721b795f254e280ffb1e00e6c4cc1d5cff57b

Please try again.

**Comment by paskal** [comment]
It fixed single page but not main page with multiply articles. Seems like it's under `body->ul->img` on main page.
I guess you should drop every `max-width` redefinition for `img` per element which is equal to `100%`, and set it globally - you don't want image to break any of the pages, are you?
And when you need lower (or higher) bound for it, then you redefine it on particular elements level (like `.article-body`).

**Comment by dim0627** [comment]
fix it.

**Comment by dim0627** [comment]
https://github.com/dim0627/hugo_theme_beg/commit/7718359506a2447ef0489dcd6bd7360f21eb93cb
