### ISSUE TITLE
Theme desing improvements

### ISSUE THREAD

**Issue by paskal** [dim0627/hugo_theme_beg#22]
beg theme is one of the best and most clear themes for blog around.
However, doing side-to-side comparison with that similar theme I'm migrating from I can see a few points which might be done smoother to improve the theme. Could you please take a look?
![image](https://user-images.githubusercontent.com/712534/33929451-9e6fa6b4-dffa-11e7-974a-eff5a02d39eb.png)
Source code for tests:
```md
### UI

[![Shinken UI](https://github.com/shinken-monitoring/mod-webui/raw/master/doc/animation.gif)](https://www.shinken-enterprise.com/en/product/)

[Shinken WebUI](https://github.com/shinken-monitoring/mod-webui/wiki) is proven itself to work well with thousands of hosts and tens of groups.

### Drawbacks

I found no visible drawbacks, based on the documentation. The only thing that concerns me is its rapid development in the past and [very slow pace of commits](https://github.com/naparuba/shinken/commits/master) in the present: around 40 commits this year; most are pull requests merged, so no new development is going on, and only community-written bugfixes are being included. It’s either too good to move on (which is never the case; even old-timers like vim and emacs get their code updated) or it’s another opensource project that not enough people care about — you should know such things before using such a complex thing as a monitoring system.

[Frédéric Mohier](https://github.com/mohierf) was very kind to give me an insight on reasons of current situation: more than one year ago, some of the main developers of Shinken left the project and made a fork named [Alignak](https://alignak-monitoring.github.io/), which is being activly developed and plan to deliver 1.0 release in December, 2016.

### Links

* [Detection and Handling of State Flapping — Shinken Manual](http://shinken.readthedocs.io/en/latest/07_advanced/flapping.html)

## [Sensu](https://sensuapp.org/)

Sensu is a monitoring framework (platform, as they call themselves) rather than complete monitoring system. Its key features include:

* Puppet \ Chef integration — define what to check and where to send messages in your configuration system
* Reusing existing technical solutions where possible, instead of inventing their own (Redis, RabbitMQ)

Sensu pulls events from queue and executes handlers on them; that’s it. Handlers can send messages, execute something on the server, or do something else you want.
```

**Comment by paskal** [comment]
And another example, which is notable because exactly same amount of information is present on the screen but it's arranged a little different - and I guess beg part could be improved a little:
![image](https://user-images.githubusercontent.com/712534/33930027-97519ce6-dffc-11e7-857e-e8dda9ee647a.png)
(Octopress part is not ideal as well, that's just out of the scope of this issue - for example, space between `<h1>` and following text in it is way too big).

**Comment by paskal** [comment]
Numbered points interval could be decreased:
![image](https://user-images.githubusercontent.com/712534/33930426-efa7905c-dffd-11e7-9ac9-26a4b4ce088e.png)
Regarding latest posts \ tags \ categories blocks:
![image](https://user-images.githubusercontent.com/712534/33930628-a3a3cf80-dffe-11e7-9379-c33c916c03b8.png)

**Comment by paskal** [comment]
And last but most important: `<strong>` must produce **bold**, `<em>` must produce *italic*.
Here is what it produces now:
![image](https://user-images.githubusercontent.com/712534/33931217-6752bd1e-e000-11e7-898c-e7782da3156d.png)
It looks like instead of italic we have bold, and instead of bold we have underscore. That's changing of very basic markdown conventions.

**Comment by dim0627** [comment]
Thanks for your suggestion 👍 
You can make PR.I'll waiting for that!
But I think you should do fork and make new theme 💯

**Comment by paskal** [comment]
I'm not sure github sent notifications to mentioned authors, so posting double there: theme highlight is out, this very theme is in it, additional info on https://github.com/paskal/terrty/issues/1.
