### ISSUE TITLE
Missing body tag causing LiveReload disabled

### ISSUE THREAD

**Issue by ghost** [dim0627/hugo_theme_beg#4]
I have modified the following files to enable LiveReload:
layouts/_default/single.html (add <body>, </body></html>)
layouts/index.html (add <body>, </body></html>)
layouts/partials/default_head.html (remove <!DOCTYPE html>)
layouts/partials/head.html (add <!DOCTYPE html>,html,head)

**Comment by paskal** [comment]
LiveReload works fine, I see no point in having open issue with bugreport noone reproduced in two years. Let's close it maybe?

**Comment by dim0627** [comment]
Yes, sorry for the late reply.
